# Node Packet

An evented binary packet and structure parser for Node.js.

## Synopsis

Use tar as an example?

## Installing

## Reference

namespace: packet

Node Packet exports the ec2 namespace, which provides the {{Structure}},
{{Parser}} and {{Serializer}} classes.

class: Structure

  parameter: pattern

  The packet pattern.

A structure is an object that both reads from and writes to a buffer
syncrhonously. When reading, buffer must contain the entire contents of the
structure. When writing, the buffer must have enough space to accomdoate the
structure.

function: read

  parameter: buffer

  The byte buffer.

  parameter: offset optional

  The optional offset into the byte buffer. Defaults to `0`.

  parameter: callback

  Called with the parameters read from the byte buffer.

The read method accepts a buffer with an optional offset. The number of
arguments is determined by the structure packet pattern, and must match
the number of arguments expected by the packet pattern.

The callback will be called with the fields read from the buffer, with the
actual count of bytes read as the last parameter.

function: write

  parameter: buffer

  The byte buffer.

Write the arguments to the  buffer at the optional offset. The arguments are
determined by the structure bit pattern. Returns the number of bytes written.

function: sizeOf

Get the size of the structure for the given variable length values. A structure
can have 0 or more variable length values.

The `sizeOf` method does not expect and will not correctly calculate the size of
the structure if fixed size value are given.

class: Parser

class: Serializer
