#!/bin/sh

set -e

rm -rf coverage

count=1;
for file in t/*/*.t.js t/*/inc/*.t.js t/*/all/*.t.js; do
  node_modules/.bin/istanbul cover \
    -x 'composers.js' \
    -x 't/require.js' -x 't/to-json.js' \
    -x 't/**/proof.js' -x 't/**/*.t.js' $file >/dev/null 2>&1
  mv coverage/coverage.json coverage/coverage$count.json
  count=$(expr $count + 1)
done

node_modules/.bin/istanbul report --root coverage --dir coverage > /dev/null

sed -i -e s,'^SF:'`pwd`/,SF:, coverage/lcov.info

exit 0
