#!/bin/sh

set -e

rm -rf coverage

count=1;
for file in $(find t -name \*.t.js); do
  echo "RUNNING $file"
  node_modules/.bin/istanbul cover \
    -x 't/require.js' -x 'ieee754.js' \
    -x 't/**/proof.js' -x 't/**/*.t.js' $file
  mv coverage/coverage.json coverage/coverage$count.json
  count=$(expr $count + 1)
done

echo "REPORTING"
node_modules/.bin/istanbul report --root coverage --dir coverage

sed -i -e s,'^SF:'`pwd`/,SF:, coverage/lcov.info

exit 0
