#!/bin/sh

set -e

echo ""

rm -f t/generated/*

(proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1

if [ $(find t -name "*.t.js.broken" | wc -c) != "0" ]; then
  echo ""
  echo "broken tests"
  echo ""
  find t -name "*.t.js.broken"
fi

if [ "$TRAVIS" = "true" ]; then
  echo "running with coverage"
  t/cover

  echo "submitting to coveralls.io"
  (cat coverage/lcov.info | node_modules/.bin/coveralls) > /dev/null 2>&1

  curl 'https://www.prettyrobots.com/travisty' | sh
fi

if [ "$TRAVIS" = "true" ] || [ "$MINIFY" = "true" ]; then
  echo ""
  echo "minified"
  echo ""

  default=$(cat composers.js | uglifyjs | gzip -c | wc -c)
  lift=$(cat composers.js | uglifyjs --lift-vars | gzip -c | wc -c)

  bak=composers-$(date +'%FT%T').js
  mv composers.js $bak
  if [ $default -lt $lift ]; then
    cat $bak | uglifyjs > composers.js
  else
    cat $bak | uglifyjs --lift-vars > composers.js
  fi

  (proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1
fi

echo ""
